name = "PackageAT"
uuid = "3b4e614f-3e99-41e3-ae89-0c289beee7c9"
version = "0.0.1"
authors = ["tripiera <anaide.tripier@sfr.fr>"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
Bonito = "4.1.9"
CSV = "0.10.15"
DataFrames = "1.8.1"
Markdown = "1.11.0"
PlotlyJS = "0.18.17"
julia = "1.10"
